name: 🐛 버그 리포트
description: 예상과 다른 동작을 보고합니다.
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: 📌 문제 설명
      description: 무엇이 문제인지 명확하고 간결하게 설명해주세요.
      placeholder: "예: 선거캠프가 빈 경우에도 UI에 표시됩니다."
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✅ 재현 방법
      description: 문제를 어떻게 재현할 수 있나요?
      placeholder: |
        1. 정당 상세 페이지로 이동
        2. 후보 클릭
        3. ...
    validations:
      required: false

  - type: input
    attributes:
      label: 💻 환경 정보
      description: 브라우저, OS 등
      placeholder: "예: Chrome 123, macOS 14"
