name: 📝 후보 정보 수정 요청
description: 후보자 관련 정보(공약, 약력, 논란 등)의 수정이 필요할 때 사용해주세요.
title: "[후보 수정 요청] {{후보자 이름}}"
labels: ["candidate-update"]
body:
  - type: input
    attributes:
      label: 🧑 후보자 이름
      description: 수정 요청할 후보의 전체 이름을 입력해주세요.
      placeholder: "예: 이재명"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: 정당
      options:
        - 더불어민주당
        - 국민의힘
        - 개혁신당
        - 진보당
        - 기본소득당
        - 새미래민주당
        - 소나무당
        - 사회대전환 연대회의
        - 자유통일당
        - 통일한국당
        - 한국국민당
        - 무소속
      description: 후보가 소속된 정당을 선택해주세요.
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✏️ 수정할 내용
      description: 수정하고자 하는 내용을 구체적으로 작성해주세요. 변경 전/후 내용을 명시해주시면 더 좋습니다.
      placeholder: |
        예시:
        - (기존) 공약: AI 투자 100조
        - (수정) 공약: AI 투자 120조

        또는
        - 논란: 날짜 오류 - 2022년 → 2023년
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🔗 출처 (선택)
      description: 뉴스 링크 또는 공식 자료가 있으면 첨부해주세요. 가능하다면 정확한 출처를 부탁드립니다.
      placeholder: "예: https://news.example.com/article/abc123"
    validations:
      required: false

  - type: textarea
    attributes:
      label: 💬 기타 의견 (선택)
      description: 추가적으로 개발자에게 전하고 싶은 말이 있다면 남겨주세요.
    validations:
      required: false

- type: markdown
  attributes:
    value: |
      ✅ 수정 요청이 완료되면 자동으로 PR과 연결될 수 있습니다. PR 작성 시 `Closes #이슈번호` 형식을 써주세요.
